### ISSUE TITLE
Feature: Add config data in file header

### ISSUE THREAD

**Issue by shujaat-github** [miyabe/encfsy#10]
@mimidesunya @miyabe 

**(Please read [2nd comment](https://github.com/mimidesunya/encfsy/issues/10#issuecomment-1471430668) and [3rd comment](https://github.com/mimidesunya/encfsy/issues/10#issuecomment-1471459615) to know why I want this)**

Can you please show me how can I add **2048 Bytes File Header** to every file that is created in **EncFSy** with **UniqueIV** set to true?  

For the time being, I write **2048 Zeros** _if they are not already written_ and then set **off** to `off += 2048` before passing to the following **write** function in **EncFSWriteFile** callback function:

`int32_t writtenLen = encfsFile->write(FileName, fileSize, (char*)Buffer, off, NumberOfBytesToWrite); ` 

But this does not work and the EncFSy throws exception.

I look forward to your help please.

**Comment by shujaat-github** [comment]
@mimidesunya I know I'm asking a bit more but I want to include the config file data (**.encfs6.xml**) inside the **header** of each file so that **EncFSy** can read the file even if I or another program such as an antivirus. etc. deletes the **.encfs6.xml** file. 

It would be very kind of you if you could please either add this feature to EncFSy or show how to do it.

Looking for your kind reply.

**Comment by shujaat-github** [comment]
@mimidesunya Adding a **config header** to every file encrypted with **EncFSy** will make that encrypted file **portable**, meaning everything needed to decrypt that file will be in the header of that file.

In the current state of EncFSy, there is a **Single Point of Failure**, i.e. if somehow **.encfs6.xml** is deleted then all encrypted files are lost as they cannot be decrypted without it.

**Comment by mimidesunya** [comment]
If UniqueIV is true, the first 8 bytes of the file contain the unique information needed for encryption and decryption.
Writing anything directly to the beginning of the file will corrupt the file.
First, the value of the EncFSVolume::HEADER_SIZEt constant would have to be changed, and other extensive modifications would be necessary. Meow!

**Comment by shujaat-github** [comment]
Thanks for the response :thumbsup:

Would it be easy if we set UniqueIV to false?

Actually I have lost my files due to .encfs6.xml corruption.

**Comment by shujaat-github** [comment]
@mimidesunya Outstanding! Superb! That worked for me! I am in love with EncFSy and the skillful developers behind it like you! :heart:

> First, the value of the EncFSVolume::HEADER_SIZEt constant would have to be changed

**Comment by mimidesunya** [comment]
You are wellcome, meow!
