### ISSUE TITLE
In function `EncFSFile::write` data type of the `fileSize` and `off` is `size_t` instead of `long`

### ISSUE THREAD

**Issue by shujaat-github** [miyabe/encfsy#12]
The `size_t `is `unsigned int` whose max value is [UINT_MAX = 4294967295 = 4.3 GB ](https://learn.microsoft.com/en-us/cpp/c-language/cpp-integer-limits?view=msvc-170) which means **maximum file size can be around 4.3 GB only.**

Isn't it a bug to use **size_t** instead of **long** here?

![image](https://github.com/mimidesunya/encfsy/assets/99479518/65e370cc-1f00-4f25-bf9d-7aa7ffed5c19)

**Comment by mimidesunya** [comment]
In 64-bit Windows, size_t is unsigned long long, meow!
