### ISSUE TITLE
What is the need for encrypting the last block of file `two times`?

### ISSUE THREAD

**Issue by shujaat-github** [miyabe/encfsy#13]
Would you be please kind enough to tell me why you encrypt the tail of the file `two times` in **streamEncrypt** function?

https://github.com/mimidesunya/encfsy/blob/16c040eb7a41f24c6b8bf62f199e82a124954f27/EncFSy_lib/EncFSUtils.hpp#L257

**Comment by mimidesunya** [comment]
I don't know, as it is an EncFS specification, meow.
