### ISSUE TITLE
does not work...

### ISSUE THREAD

**Issue by Unixware** [miyabe/encfsy#2]
Just installed it , dokan is 1.5.1.1000, but the encfsy complaints "Can't assign a drive letter" , no matter if I run this on gui - even as "admin". (windows 10 21H2 x64 )

**Comment by miyabe** [comment]
I couldn't reproduce the problem. Will it happen many times?

**Comment by Unixware** [comment]
oops. false alarm, that works, looks like I had to restart the PC after installing the Dokan ... thanks :-}
