### ISSUE TITLE
compiler question

### ISSUE THREAD

**Issue by lonnietc** [miyabe/encfsy#6]
Hello,

I was just trying to compile Encfsy with VS2019 and it seems that it needs SDK 143 which does not come in that version, but I think is available in VS2022.

Can you please tell me what version of Visual Studio you used?

Also, I am seeking someone who might be interested in working on a C++ SSHFS version that can compile under the latest Dokany. I have seen that there is a C# version available, but I am seeking a C++ version.

Would you be interested?
Thanks

**Comment by mimidesunya** [comment]
I used VC2022, meow!
Unfortunately I have my hands full with the development of EncFS.

**Comment by lonnietc** [comment]
Thanks for getting back to me and I also understand. No worries.

Also, just came across WinFSP FUSE and was wondering what you thought of it as compared to Dokany?

They seem similar, but I have also ready that WinFSP is faster, more mature, and more stable.

Any thoughts?

**Comment by mimidesunya** [comment]
I don't know at the moment.
You may want to see if it support Alternative Data Stream, Mount Manager and ignores case of file names.
Meow!

**Comment by lonnietc** [comment]
Thanks and I will look into it more to see what I can find out.

Happy Holidays to you and your family.
