### ISSUE TITLE
Support for disabling Directory Names Encoding.

### ISSUE THREAD

**Issue by shujaat-github** [miyabe/encfsy#7]
Currently EncFSy **encodes** both **directory** and **file** names. I have come across a need to disable directory names encoding. It would be so wonderful if you please add this feature in EncFSy.

**Comment by shujaatak** [comment]
:star_struck: @miyabe Happy New Year :star_struck:

**Comment by mimidesunya** [comment]
There is no such option in EncFS.
It is better not to do this because the contents can be guessed from the file name.
Meow！

**Comment by shujaat-github** [comment]
Thank you for your response.

I am looking to only disable **Folder Names** Encryption.

**Comment by mimidesunya** [comment]
I think the same problem would occur if only folder names, meow...
