### ISSUE TITLE
Microsoft Visio file gets corrupted.

### ISSUE THREAD

**Issue by shujaat-github** [miyabe/encfsy#8]
Visio file gets corrupted if it is saved after **relocating** an **existing** component i.e. rectangle, circle, square, etc.

**Steps to reproduce:**

- Create a Visio document, place in it some components i.e. rectangles, squares, circles, etc. then Ctrl+S to save and then Close it.
- Reopen the same document, which it does open successfully, however move and change location of an existing component and then save and close it.
- Now again try to open the same document, but, unfortunately this time it would not open, instead Visio will show this message:
![image](https://user-images.githubusercontent.com/99479518/210517174-59cfbb36-907e-4326-834e-59a8964d5333.png)

**I use Microsoft Visio 2019:**

![image](https://user-images.githubusercontent.com/99479518/210515660-7d42e080-21cd-4bef-a987-5e04b489ec10.png)

**Comment by shujaat-github** [comment]
Hi @mimidesunya, I know you're probably busy with your amazing projects, but I have run into an issue where Visio is unable to be encrypted using EncFS because it becomes corrupted. I and every other user of the EncFSy would really appreciate it if you could take a look and see if you can fix it. Thank you for your help!

**Comment by shujaat-github** [comment]
I am concerned about this issue and would greatly appreciate it if it is resolved soon.

**Comment by mimidesunya** [comment]
My Visio trial license has expired.
So I will talk to my boss, meow...

**Comment by shujaat-github** [comment]
Thank you for your reply, I would greatly appreciate a prompt solution to this problem.

**Comment by shujaat-github** [comment]
@mimidesunya You can use Visio or any other trial software by installing it on a **new virtual machine** within **[VirtualBox](https://www.virtualbox.org/)**.

**Comment by shujaat-github** [comment]
[VMware ](https://www.vmware.com/products/workstation-pro/workstation-pro-evaluation.html)can also be used in place of [VirtualBox ](https://www.virtualbox.org/)to create virtual machines.

**Comment by shujaat-github** [comment]
@mimidesunya It would be so kind of you if you please fix this issue. This is the only issue I face with Awesome EncFSy.

**Comment by mimidesunya** [comment]
Sorry for the delay.
I have released a fixed version.
Meow!

**Comment by shujaat-github** [comment]
Awesome! I just tested that the issue with Visio has been resolved. **Thank you!** 

I will now perform **regression testing** on other file formats and get back to you with the results soon.

**Comment by shujaat-github** [comment]
EncFSy crashed while attempting to open a **large collection of images** in various formats (png, jpg, bmp, jfif, webp, wbmp, and svg). I am reporting this issue even though I don't have a clear, reproducible example at this time. I will provide a minimal reproducible example as soon as I discover it.

**Comment by shujaat-github** [comment]
I suspect **low memory** is the root cause of the EncFSy crash while opening a big list of images. My system has 16GB RAM and it **reaches full utilization** when opening a large image collection, which **I think** leads to the EncFSy crash.

**I'll report any further findings in a separate issue, and for now, this issue can be considered closed.**
